name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Flutter action
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: 3.27.3
      - name: Build
      - run: flutter pub get
      - run: flutter build apk
      - run: mv ./build/app/outputs/flutter-apk/app-release.apk ./katigatey.apk
      - name: Release 
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./katigatey.apk
